#!/bin/bash

for COMMIT in $( git blame errata.tex | grep -o '% merge of.\+' | grep -o '[^ ]\+$' ); do
    MERGE=$(git log "$COMMIT..master" --ancestry-path --merges --oneline | grep -o '^[^ ]\+' | xargs git describe | sed s/first-edition-//)
    echo Marking $COMMIT as $MERGE
    sed -i "s/% merge of $COMMIT/$MERGE/g" errata.tex
done
